# Generated by Django 3.2.6 on 2021-09-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogdb_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogdb',
            new_name='Blog',
        ),
    ]
